// This file is generated by New-Parser.ps1; do not edit manually.
#include <ookii/command_line.h>
#include "../input/action_arguments.h"
    
std::optional<my_arguments> my_arguments::parse(int argc, const char *const argv[], ookii::basic_usage_writer<char> *options, ookii::basic_localized_string_provider<char> *string_provider)
{
    auto name = ookii::basic_command_line_parser<char>::get_executable_name(argc, argv);
    my_arguments args{};
    auto parser = ookii::basic_parser_builder<char>{name, string_provider}
        .add_action_argument(static_action, "StaticAction").required().positional()
        .add_action_argument([&args](some<template_type<with, nesting>> value, ookii::basic_command_line_parser<char> &parser) { return args.instance_action(value, parser); }, "InstanceAction")
        .build();

    if (parser.parse(argc, argv, options))
    {
        return args;
    }

    return {};
}


