// This file is generated by New-Parser.ps1; do not edit manually.
#include <ookii/command_line.h>
#include "../input/arguments.h"
    
ookii::basic_parser_builder<char> my_arguments::create_builder(std::basic_string<char> command_name, ookii::basic_localized_string_provider<char> *string_provider, const std::locale &locale)
{
    command_name = "name";
    ookii::basic_parser_builder<char> builder{command_name, string_provider};
    builder
        .locale(locale)
        .description("Description of the arguments with a line break.\n\nAnd a paragraph.")
        .add_argument(this->test_arg, "TestArg").required().positional().description("Argument description with a line break.\n\nAnd another paragraph.")
        .add_argument(this->__test__arg2__, "TestArg2").positional().default_value(1).value_description("desc").alias("test").description("Short description.")
        .add_multi_value_argument(this->test_arg3, "foo").alias("t").alias("v")
        .add_argument(this->_testArg4, "TestArg4").cancel_parsing()
        .add_argument(this->TestArg5, "TestArg5").default_value("foo")
    ;

    return builder;
}

int main(int argc, char *argv[])
{
    auto args = my_arguments::parse(argc, argv);
    if (!args)
        return 1;

    return my_entry(*args);
}

