// This file is generated by New-Parser.ps1; do not edit manually.
#include <ookii/command_line.h>
#include "../input/long_short.h"
    
ookii::basic_parser_builder<char> my_arguments::create_builder(std::basic_string<char> command_name, ookii::basic_localized_string_provider<char> *string_provider, const std::locale &locale)
{
    ookii::basic_parser_builder<char> builder{command_name, string_provider};
    builder
        .locale(locale)
        .mode(ookii::parsing_mode::long_short)
        .case_sensitive(true)
        .add_argument(this->test_arg, "test-arg").short_name().required().positional()
        .add_argument(this->test_arg2, "test-arg2").short_name('s').short_alias('x').short_alias('y')
        .add_argument(this->foo, 'f')
        .add_argument(this->bar, 'o')
    ;

    return builder;
}


