// This file is generated by New-Parser.ps1; do not edit manually.
#include <ookii/command_line.h>
#include "../input/action_arguments.h"
    
ookii::basic_parser_builder<char> my_arguments::create_builder(std::basic_string<char> command_name, ookii::basic_localized_string_provider<char> *string_provider, const std::locale &locale)
{
    ookii::basic_parser_builder<char> builder{command_name, string_provider};
    builder
        .locale(locale)
        .add_action_argument(static_action, "StaticAction").required().positional()
        .add_action_argument([this](some<template_type<with, nesting>> value, ookii::basic_command_line_parser<char> &parser) { return this->instance_action(value, parser); }, "InstanceAction")
    ;

    return builder;
}


