// This file is generated by New-Subcommand.ps1; do not edit manually.
#include <ookii/command_line.h>
#include <ookii/command_line_generated.h>
#include "../input/subcommand_global.h"
    
my_command::my_command(my_command::builder_type &builder)
    : ookii::command{builder}
{
    builder
        .add_argument(this->test_arg, "test-arg").required().positional()
    ;
}

ookii::basic_command_manager<char> ookii::register_commands(std::basic_string<char> application_name, ::ookii::basic_localized_string_provider<char> *string_provider, const std::locale& locale)
{
    basic_command_manager<char> manager{application_name, true, locale, string_provider};
    manager
        .description("Description of the application.")
        .common_help_argument("--help")
        .configure_parser([](auto &parser)
        {
            parser
                .mode(ookii::parsing_mode::long_short)
                .prefixes({ "-", "/" })
            ;
        })
#ifdef _WIN32
        .add_win32_version_command()
#else
        .add_version_command([]()
        {
            ookii::console_stream<char>::cout() << "Version info" << std::endl;
        })
#endif
        .add_command<my_command>("name", "Description of the command with a line break.\n\nAnd a paragraph.")
    ;

    return manager;
}


