// This file is generated by New-Parser.ps1; do not edit manually.
#include <filesystem>
#include <ookii/command_line.h>
#include "../input/long_short.h"
    
std::optional<my_arguments> my_arguments::parse(int argc, const char *const argv[], ookii::basic_usage_writer<char> *options, ookii::basic_localized_string_provider<char> *string_provider)
{
    auto name = ookii::basic_command_line_parser<char>::get_executable_name(argc, argv);
    my_arguments args{};
    auto parser = ookii::basic_parser_builder<char>{name, string_provider}
        .mode(ookii::parsing_mode::long_short)
        .case_sensitive(true)
        .add_argument(args.test_arg, "test-arg").short_name().required().positional()
        .add_argument(args.test_arg2, "test-arg2").short_name('s').short_alias('x').short_alias('y')
        .add_argument(args.foo, 'f')
        .add_argument(args.bar, 'o')
        .build();

    if (parser.parse(argc, argv, options))
    {
        return args;
    }

    return {};
}


