// This file is generated by New-Parser.ps1; do not edit manually.
#include <filesystem>
#include <ookii/command_line.h>
#include "../input/arguments.h"
    
std::optional<my_arguments> my_arguments::parse(int argc, const char *const argv[], ookii::basic_usage_writer<char> *options, ookii::basic_localized_string_provider<char> *string_provider)
{
    auto name = "name";
    my_arguments args{};
    auto parser = ookii::basic_parser_builder<char>{name, string_provider}
        .description("Description of the arguments with a line break.\n\nAnd a paragraph.")
        .add_argument(args.test_arg, "TestArg").required().positional().description("Argument description with a line break.\n\nAnd another paragraph.")
        .add_argument(args.__test__arg2__, "TestArg2").positional().default_value(1).value_description("desc").alias("test").description("Short description.")
        .add_multi_value_argument(args.test_arg3, "foo").alias("t").alias("v")
        .add_argument(args._testArg4, "TestArg4").cancel_parsing()
        .add_argument(args.TestArg5, "TestArg5").default_value("foo")
        .build();

    if (parser.parse(argc, argv, options))
    {
        return args;
    }

    return {};
}

int main(int argc, char *argv[])
{
    auto args = my_arguments::parse(argc, argv);
    if (!args)
        return 1;

    return my_entry(*args);
}

