// This file is generated by New-Parser.ps1; do not edit manually.
#include <filesystem>
#include <ookii/command_line.h>
#include "../input/arguments.h"
#include "../input/arguments2.h"
    
std::optional<my_arguments> my_arguments::parse(int argc, const wchar_t *const argv[], const ookii::basic_usage_options<wchar_t> &options)
{
    auto name = L"name";
    my_arguments args{};
    auto parser = ookii::basic_parser_builder<wchar_t>{name}
        .description(L"Description of the arguments with a line break.\n\nAnd a paragraph.")
        .add_argument(args.test_arg, L"TestArg").required().positional().description(L"Argument description with a line break.\n\nAnd another paragraph.")
        .add_argument(args.__test__arg2__, L"TestArg2").positional().default_value(1).value_description(L"desc").alias(L"test").description(L"Short description.")
        .add_multi_value_argument(args.test_arg3, L"foo").alias(L"t").alias(L"v")
        .add_argument(args._testArg4, L"TestArg4").cancel_parsing()
        .add_argument(args.TestArg5, L"TestArg5").default_value("foo")
        .build();

    if (parser.parse(argc, argv, options))
    {
        return args;
    }

    return {};
}

std::optional<other_arguments> other_arguments::parse(int argc, const wchar_t *const argv[], const ookii::basic_usage_options<wchar_t> &options)
{
    std::basic_string<wchar_t> name;
    if (argc > 0) { name = std::filesystem::path{argv[0]}.filename().wstring(); }
    other_arguments args{};
    auto parser = ookii::basic_parser_builder<wchar_t>{name}
        .prefixes({ L"--", L"-" })
        .case_sensitive(true)
        .allow_whitespace_separator(false)
        .allow_duplicate_arguments(true)
        .argument_value_separator(L'=')
        .add_argument(args.some_arg, L"SomeArg")
        .build();

    if (parser.parse(argc, argv, options))
    {
        return args;
    }

    return {};
}

std::optional<third_arguments> third_arguments::parse(int argc, const wchar_t *const argv[], const ookii::basic_usage_options<wchar_t> &options)
{
    std::basic_string<wchar_t> name;
    if (argc > 0) { name = std::filesystem::path{argv[0]}.filename().wstring(); }
    third_arguments args{};
    auto parser = ookii::basic_parser_builder<wchar_t>{name}
        .add_argument(args.other_arg, L"OtherArg")
        .build();

    if (parser.parse(argc, argv, options))
    {
        return args;
    }

    return {};
}


