// This file is generated by New-Subcommand.ps1; do not edit manually.
#include <filesystem>
#include <ookii/command_line.h>
#include <ookii/command_line_generated.h>
#include "../input/subcommand_global.h"
    
my_command::my_command(my_command::builder_type &builder)
    : ookii::command{builder}
{
    builder
        .add_argument(this->test_arg, "TestArg").required().positional();
}

ookii::basic_command_manager<char> ookii::register_commands(std::basic_string<char> application_name)
{
    basic_command_manager<char> manager{application_name};
    manager
        .configure_parser([](auto &parser)
        {
            parser
                .mode(ookii::parsing_mode::long_short)
                .prefixes({ "-", "/" });
        })
        .add_command<my_command>("name", "Description of the command with a line break.\n\nAnd a paragraph.");

    return manager;
}


