// This file is generated by New-Parser.ps1; do not edit manually.
#include <filesystem>
#include <ookii/command_line.h>
#include "..\samples\generated_parser\arguments.h"
    
std::optional<arguments> arguments::parse(int argc, const char *const argv[], const ookii::basic_usage_options<char> &options)
{
    std::basic_string<char> name;
    if (argc > 0) { name = std::filesystem::path{argv[0]}.filename().string(); }
    arguments args{};
    auto parser = ookii::basic_parser_builder<char>{name}
        .description("Sample command line application. The application parses the command line and prints the results, but otherwise does nothing and none of the arguments are actually used for anything.")
        .add_argument(args.source, "source").required().positional().description("The source data.")
        .add_argument(args.destination, "destination").required().positional().description("The destination data.")
        .add_argument(args.operation_index, "operation_index").positional().default_value(1).description("The operation's index.")
        .add_argument(args.count, "count").value_description("number").description("Provides the count for something to the application.")
        .add_argument(args.verbose, "verbose").alias("v").description("Print verbose information; this is an example of a switch argument.")
        .add_multi_value_argument(args.values, "Value").description("This is an example of a multi-value argument, which can be repeated multiple times to set more than one value.")
        .add_argument(args.help, "help").cancel_parsing().alias("?").description("Displays this help message.")
        .build();

    if (parser.parse(argc, argv, options))
    {
        return args;
    }

    return {};
}


